version: "3"

services:
  base-app:
    build:
      context: .
    labels:
      maintaner: "Fabio Thomaz Molinar"
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    env_file: .env
    container_name: base-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
